### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by brettle** [PauliBuccini/meteor-accounts-linkedin#12]
Same issue as mentioned in issue PauliBuccini/meteor-linkedin#7. I've found a bug and would like to contribute a fix but need to know the license first.

I notice that your package is a fork of @yefim's package so I mentioning him here in hopes that he will indicate the license associated with his original repo.

**Comment by Merkurijus** [comment]
Added MIT licence

**Comment by brettle** [comment]
Thanks!
