### ISSUE TITLE
Unable to parse state from OAuth query

### ISSUE THREAD

**Issue by landland** [PauliBuccini/meteor-accounts-linkedin#4]
Hi, I'm getting the following error while trying out this package and not able to login with LinkedIn.

>Unable to parse state from OAuth query: ?<i?rV↨iOZ♥OWj1.t♀?m½ nxµ&E¡⌂áAR
Unable to parse state from OAuth query: ?<i?rV↨iOZ♥OWj1.t♀?m½ nxµ&E¡⌂áAR
Unable to parse state from OAuth query: ?<i?rV↨iOZ♥OWj1.t♀?m½ nxµ&E¡⌂áAR
Error in OAuth Server: Failed to complete OAuth handshake with LinkedIn. failed [400] {"error_description":"missing required parameters, includes an invalid parameter value, parameter more than once. : Unable to retrieve access token : appId or redirect uri does not match authorization code or authorization code expired","error":"invalid_request"}

Here's my server side configuration

          ServiceConfiguration.configurations.remove({
                service: "linkedin"
           });
            ServiceConfiguration.configurations.insert({
                service: "linkedin",
                clientId: <my clientid>,
                secret: <my secret>
            });

And on client side event I do

     Meteor.loginWithLinkedin({}, function(err) {
            if (err) {
                console.log("ERROR: ", err.message); //error handling
            } else {
                console.log("NO ERROR ON LOGIN");
            }
        });

Saw this error here as well

https://github.com/yubozhao/meteor-accounts-instagram/issues/3

**Comment by landland** [comment]
hi @PauliBuccini have you had a chance to look at this?

**Comment by wulfmeister** [comment]
Getting this error as well.

**Comment by rrova** [comment]
I'm getting this error also.

**Comment by gwendall** [comment]
+1

**Comment by wulfmeister** [comment]
It works for me after adding the code in this PR:  https://github.com/PauliBuccini/meteor-linkedin/pull/2

**Comment by rrova** [comment]
That worked for me also.

**Comment by wulfmeister** [comment]
Great!  I'm glad :)

**Comment by keyscores** [comment]
This still happens occasionally on local env. It will work after >meteor reset 

Packages:
accounts-facebook              1.0.4  Login service for Facebook accounts
accounts-google                1.0.4  Login service for Google accounts
accounts-ui-unstyled           1.1.7  Unstyled version of login widgets
houston:admin                  2.0.3  A zero-config Meteor Admin
iron:router                    1.0.7  Routing specifically designed for Meteor
meteor-platform                1.2.2  Include a standard set of Meteor packages in your app
pauli:accounts-linkedin        1.1.2  Accounts service for LinkedIn accounts
service-configuration          1.0.4  Manage the configuration for third-party services

**Comment by PauliBuccini** [comment]
Hi @keyscores , 
well it is a bit strange, currently I am on the road and hitting deadlines on some work, but hopefully within week, I go through package and will look for any inconsistencies.

**Comment by keyscores** [comment]
Thanks for the help. I'm seeing an issue with production as well, and it's failing silently (no console logs).

Click login -> Sends to Linkedin -> back to page without having logged in (or any db inserts).

Are there any logs anywhere?

**Comment by timmakken** [comment]
The comment from @wulfmeister helped me getting access to login with linkedin however as @keyscores is saying the login on the app does not actually work after logging in with linkedin.

**Comment by wulfmeister** [comment]
The package has since been updated beyond my PR.  I'm using the normal atmosphere version now, and it's working great.  Are you using an older version with my PR?

**Comment by timmakken** [comment]
Just tested , and it works with the new update :+1: Great job , and i am very happy to see this package is kept up to date!

**Comment by wulfmeister** [comment]
:+1:

**Comment by keyscores** [comment]
I haven't had this issue in a long time. Been trying to replicate, but never produced the error again. 
From my point of view this ticket can be closed.
