### ISSUE TITLE
Nothing Happening when doing Meteor.loginWithLinkedin(...)

### ISSUE THREAD

**Issue by ashah888** [PauliBuccini/meteor-accounts-linkedin#5]
Hi Pauli,

I installed your package and tried to login using Meteor.loginWithLinkedin(...)

However nothing happens when doing this code. The function works and there are no errors but there is no popup either.

Any idea why?

**Comment by PauliBuccini** [comment]
Do you still facing issue, @ashah888 ?

**Comment by ktruckenmiller** [comment]
Yeah I'm having this issue right now when I deploy to app.meteor.com - but it works fine on my local build.

**Comment by PauliBuccini** [comment]
@ktruckenmiller Do you have this issue on non meteor.com server, like DO, or modulus ?

**Comment by ktruckenmiller** [comment]
I got modulus working - had to add the endpoints from linkedin - I think that was the issue. I'll get back to you once I try and launch on an EC2 again.

**Comment by ktruckenmiller** [comment]
On modulus I didn't have the issue, but on *.meteor.com I still can't get passed it.

**Comment by fpoirier1** [comment]
Samething here. Any idea ??
