### ISSUE TITLE
Field name conflicts upon creating new user

### ISSUE THREAD

**Issue by v3rron** [PauliBuccini/meteor-accounts-linkedin#8]
I'm having a weird issue with Meteor.loginWithLinkedin function. I'm using Collection2 for Schema settings and my user.profile schema looks like that.
```
Schemas.UserProfile = new SimpleSchema({
    full_name: {
        type: String,
        regEx: /^[a-zA-Z -]{2,64}$/,
        optional: true
    },
    about: {
        type: String,
        defaultValue: ''
    },
    skills: {
        type: [Skills],
        optional: true
    },
});
```
The problem is with my skills array field in UserProfile. I'm using my own skills system and it works perfectly in app. But since LinkedIn also returns "skills" object upon authorization I get this error when creating new user: 
```
I20150430-20:25:43.304(-4)? Exception while invoking method 'login' Error: Skills must be an array
I20150430-20:25:43.304(-4)?     at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
I20150430-20:25:43.304(-4)?     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
I20150430-20:25:43.305(-4)?     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
I20150430-20:25:43.305(-4)?     at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:1017:1)
I20150430-20:25:43.305(-4)?     at Object.Accounts.updateOrCreateUserFromExternalService (packages/accounts-base/accounts_server.js:1164:1)
I20150430-20:25:43.305(-4)?     at Object.updateOrCreateUserFromExternalService (packages/splendido:accounts-meld/lib/accounts-meld-server.js:635:1)
I20150430-20:25:43.305(-4)?     at [object Object].Package (packages/accounts-oauth/oauth_server.js:45:1)
I20150430-20:25:43.305(-4)?     at packages/accounts-base/accounts_server.js:358:1
I20150430-20:25:43.305(-4)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:161:1)
I20150430-20:25:43.305(-4)?     at runLoginHandlers (packages/accounts-base/accounts_server.js:355:1)
```
**When I'm removing "skills" field from UserProfile Schema, everything works fine and user is created and being logged in automatically.**
**I'm assuming that Meteor.loginWithLinkedin is trying to match the fields from response and insert them into profile automatically which I do not need (I'm using my own skill system).**
I tried to bypass it with collection2 before filter hooks like that:
```
Meteor.users.before.insert(function(userId, user){
    if(typeof(user.services.linkedin) != "undefined"){
        console.log(user.services.linkedin);
        delete user.services.linkedin.skills;
    }
});
```
**But this never gets called because the error happens before that hook.**
**Is there a way to prevent the UserProfile to be filled automatically with matching fields?**

PS: I'm also using Meteor.loginWithGoogle in my app and don't have those issues.

**Comment by timmakken** [comment]
Im experiencing a similar issue here, its not possible to set the package preset field to something else for some reason

**Comment by PauliBuccini** [comment]
Happy for pull request:), but I will be doing some refactoring in coming week for package, will look, at all request

**Comment by v3rron** [comment]
Ended up emptying user.profile object and reentering all the necessary values myself.
````
//  server/accounts.js
Accounts.onCreateUser(function (options, user) {
    if (typeof(user.services.linkedin) !== "undefined") {
        user.profile = {};
        var linkedinService = user.services.linkedin;
        user.profile.title = linkedinService.headline;
        return user;
    }
}
````
